exclude: &exclude
  exclude-filter: "(?i)套餐|到期|有效|剩余|版本|已用|过期|失联|测试|官方|网址|备用|群|TEST|客服|网站|获取|订阅|流量|机场|下次|官址|联系|邮箱|工单|学术|USE|USED|TOTAL|EXPIRE|EMAIL|如果|更新"
info-filter: &info-filter
  filter: "(?i)套餐|到期|有效|剩余|版本|已用|过期|失联|测试|官方|网址|备用|群|TEST|客服|网站|获取|订阅|流量|机场|下次|官址|联系|邮箱|工单|学术|USE|USED|TOTAL|EXPIRE|EMAIL|如果|更新"
# 代理集
proxy-providers:
  provider1:
    type: http
    # 填写订阅地址
    url:
    # 12 小时更新
    interval: 43200
    header:
    User-Agent:
      - "clash.meta"
      - "mihomo/1.19.22"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 5000
# 代理组
proxy-groups:
  - name: 节点选择
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png"
    proxies:
      - 自动选择
      - 故障转移
      - 负载均衡
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DIRECT
  - name: 手动切换
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png"
    include-all: true
    <<: *exclude
  - name: 自动选择
    type: url-test
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png"
    url: http://www.gstatic.com/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    <<: *exclude
  - name: 故障转移
    type: fallback
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Magic.png"
    url: http://www.gstatic.com/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    <<: *exclude
  - name: 负载均衡
    type: load-balance
    strategy: consistent-hashing
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Stack.png"
    url: http://www.gstatic.com/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    <<: *exclude
  - name: 电报消息
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png"
    proxies:
      - 节点选择
      - 自动选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DIRECT
  - name: Ai平台
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AI.png"
    proxies:
      - 节点选择
      - 自动选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DIRECT
  - name: 油管视频
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png"
    proxies:
      - "节点选择"
      - "自动选择"
      - "香港节点"
      - "台湾节点"
      - "狮城节点"
      - "日本节点"
      - "美国节点"
      - "韩国节点"
      - "手动切换"
      - "DIRECT"
  - name: 奈飞视频
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png"
    proxies:
      - "奈飞节点"
      - "节点选择"
      - "自动选择"
      - "故障转移"
      - "负载均衡"
      - "香港节点"
      - "台湾节点"
      - "狮城节点"
      - "日本节点"
      - "美国节点"
      - "韩国节点"
      - "手动切换"
      - "DIRECT"
  - name: 巴哈姆特
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bahamut.png"
    proxies:
      - 节点选择
      - 台湾节点
      - 手动切换
      - DIRECT
  - name: 哔哩哔哩
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/bilibili.png"
    proxies:
      - 全球直连
      - 台湾节点
      - 香港节点
  - name: 国外媒体
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/mini/GlobalMedia.png"
    proxies:
      - 节点选择
      - 自动选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DIRECT
  - name: 国内媒体
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/DomesticMedia.png"
    proxies:
      - DIRECT
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 手动切换
  - name: 谷歌FCM
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png"
    proxies:
      - DIRECT
      - 节点选择
      - 美国节点
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 韩国节点
      - 手动切换
  - name: 微软Bing
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/bing.png"
    proxies:
      - DIRECT
      - 节点选择
      - 美国节点
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 韩国节点
      - 手动切换
  - name: 微软云盘
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/OneDrive.png"
    proxies:
      - DIRECT
      - 节点选择
      - 美国节点
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 韩国节点
      - 手动切换
  - name: 微软服务
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png"
    proxies:
      - DIRECT
      - 节点选择
      - 美国节点
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 韩国节点
      - 手动切换
  - name: 苹果服务
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png"
    proxies:
      - DIRECT
      - 节点选择
      - 美国节点
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 韩国节点
      - 手动切换
  - name: 游戏平台
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png"
    proxies:
      - DIRECT
      - 节点选择
      - 美国节点
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 韩国节点
      - 手动切换
  - name: 网易音乐
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netease_Music.png"
    proxies:
      - DIRECT
      - 节点选择
      - 自动选择
    filter: "(?i)网易|音乐|解锁|Music|NetEase"
  - name: 全球直连
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png"
    proxies:
      - DIRECT
      - 节点选择
      - 自动选择
  - name: 广告拦截
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png"
    proxies:
      - REJECT
      - DIRECT
  - name: 应用净化
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hijacking.png"
    proxies:
      - REJECT
      - DIRECT
  - name: AdBlock
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png"
    proxies:
      - REJECT
      - DIRECT
  - name: 隐私防护
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hijacking.png"
    proxies:
      - REJECT
      - DIRECT
  - name: 香港节点
    type: url-test
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png"
    url: "http://www.gstatic.com/generate_204"
    include-all: true
    interval: 300
    tolerance: 50
    filter: "(?i)港|HK|hk|Hong Kong|HongKong|hongkong"
  - name: 日本节点
    type: url-test
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png"
    url: http://www.gstatic.com/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    filter: "(?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan"
  - name: 美国节点
    type: url-test
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png"
    url: http://www.gstatic.com/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    filter: "(?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States"
  - name: 台湾节点
    type: url-test
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png"
    include-all: true
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    filter: "(?i)台|新北|彰化|TW|Taiwan"
  - name: 狮城节点
    type: url-test
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png"
    include-all: true
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    filter: "(?i)新加坡|坡|狮城|SG|Singapore"
  - name: 韩国节点
    type: url-test
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Korea.png"
    url: http://www.gstatic.com/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    filter: "(?i)KR|Korea|KOR|首尔|韩|韓"
  - name: 奈飞节点
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png"
    include-all: true
    filter: "(?i)NF|奈飞|解锁|Netflix|NETFLIX|Media"
  - name: 漏网之鱼
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png"
    proxies:
      - 节点选择
      - 自动选择
      - 故障转移
      - 负载均衡
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DIRECT
  - name: 订阅信息
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Airport.png"
    use: provider1
    <<: *info-filter
  - name: GLOBAL
    type: select
    icon: "https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png"
    proxies:
      - DIRECT
    include-all: true
    <<: *exclude

# 规则
rules:
  - RULE-SET,mobai-direct,DIRECT
  - RULE-SET,ACL4SSR-LocalAreaNetwork,全球直连
  - RULE-SET,ACL4SSR-UnBan,全球直连
  - RULE-SET,ACL4SSR-BanAD,广告拦截
  - RULE-SET,ACL4SSR-BanProgramAD,应用净化
  - RULE-SET,ACL4SSR-BanEasyList,AdBlock
  - RULE-SET,ACL4SSR-BanEasyListChina,AdBlock
  - RULE-SET,ACL4SSR-BanEasyPrivacy,隐私防护
  - RULE-SET,ACL4SSR-GoogleFCM,谷歌FCM
  - RULE-SET,ACL4SSR-GoogleCN,全球直连
  - RULE-SET,ACL4SSR-SteamCN,全球直连
  - RULE-SET,ACL4SSR-Bing,微软Bing
  - RULE-SET,ACL4SSR-OneDrive,微软云盘
  - RULE-SET,ACL4SSR-Microsoft,微软服务
  - RULE-SET,ACL4SSR-Apple,苹果服务
  - RULE-SET,ACL4SSR-Telegram,电报消息
  - RULE-SET,ACL4SSR-AI,Ai平台
  - RULE-SET,ACL4SSR-OpenAi,Ai平台
  - RULE-SET,ACL4SSR-NetEaseMusic,网易音乐
  - RULE-SET,ACL4SSR-Epic,游戏平台
  - RULE-SET,ACL4SSR-Origin,游戏平台
  - RULE-SET,ACL4SSR-Sony,游戏平台
  - RULE-SET,ACL4SSR-Steam,游戏平台
  - RULE-SET,ACL4SSR-Nintendo,游戏平台
  - RULE-SET,ACL4SSR-YouTube,油管视频
  - RULE-SET,ACL4SSR-Netflix,奈飞视频
  - RULE-SET,ACL4SSR-Bahamut,巴哈姆特
  - RULE-SET,ACL4SSR-BilibiliHMT,哔哩哔哩
  - RULE-SET,ACL4SSR-Bilibili,哔哩哔哩
  - RULE-SET,ACL4SSR-ChinaMedia,国内媒体
  - RULE-SET,ACL4SSR-ProxyMedia,国外媒体
  - RULE-SET,ACL4SSR-ProxyGFWlist,节点选择
  - RULE-SET,ACL4SSR-ChinaDomain,全球直连
  - RULE-SET,ACL4SSR-ChinaCompanyIp,全球直连
  - RULE-SET,ACL4SSR-Download,全球直连
  - GEOIP,CN,全球直连
  - MATCH,漏网之鱼
# 规则集
rule-providers:
  mobai-direct:
    type: http
    behavior: classical
    format: yaml
    url: "https://testingcf.jsdelivr.net/gh/Qian-MoBai/rules/clash/rules/direct.yaml"
    interval: 43200
  ACL4SSR-LocalAreaNetwork:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/LocalAreaNetwork.list"
    interval: 43200
  ACL4SSR-UnBan:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/UnBan.list"
    interval: 43200
  ACL4SSR-BanAD:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanAD.list"
    interval: 43200
  ACL4SSR-BanProgramAD:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanProgramAD.list"
    interval: 43200
  ACL4SSR-BanEasyList:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanEasyList.list"
    interval: 43200
  ACL4SSR-BanEasyListChina:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanEasyListChina.list"
    interval: 43200
  ACL4SSR-BanEasyPrivacy:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanEasyPrivacy.list"
    interval: 43200
  ACL4SSR-GoogleFCM:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/GoogleFCM.list"
    interval: 43200
  ACL4SSR-GoogleCN:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/GoogleCN.list"
    interval: 43200
  ACL4SSR-SteamCN:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/SteamCN.list"
    interval: 43200
  ACL4SSR-Bing:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Bing.list"
    interval: 43200
  ACL4SSR-OneDrive:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/OneDrive.list"
    interval: 43200
  ACL4SSR-Microsoft:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Microsoft.list"
    interval: 43200
  ACL4SSR-Apple:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Apple.list"
    interval: 43200
  ACL4SSR-Telegram:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Telegram.list"
    interval: 43200
  ACL4SSR-AI:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/AI.list"
    interval: 43200
  ACL4SSR-OpenAi:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/OpenAi.list"
    interval: 43200
  ACL4SSR-NetEaseMusic:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/NetEaseMusic.list"
    interval: 43200
  ACL4SSR-Epic:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Epic.list"
    interval: 43200
  ACL4SSR-Origin:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Origin.list"
    interval: 43200
  ACL4SSR-Sony:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Sony.list"
    interval: 43200
  ACL4SSR-Steam:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Steam.list"
    interval: 43200
  ACL4SSR-Nintendo:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Nintendo.list"
    interval: 43200
  ACL4SSR-YouTube:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/YouTube.list"
    interval: 43200
  ACL4SSR-Netflix:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Netflix.list"
    interval: 43200
  ACL4SSR-Bahamut:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Bahamut.list"
    interval: 43200
  ACL4SSR-BilibiliHMT:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/BilibiliHMT.list"
    interval: 43200
  ACL4SSR-Bilibili:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Bilibili.list"
    interval: 43200
  ACL4SSR-ChinaMedia:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaMedia.list"
    interval: 43200
  ACL4SSR-ProxyMedia:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyMedia.list"
    interval: 43200
  ACL4SSR-ProxyGFWlist:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyGFWlist.list"
    interval: 43200
  ACL4SSR-ChinaDomain:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaDomain.list"
    interval: 43200
  ACL4SSR-ChinaCompanyIp:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaCompanyIp.list"
    interval: 43200
  ACL4SSR-Download:
    type: http
    behavior: classical
    format: text
    url: "https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Download.list"
    interval: 43200
